services:
  reparer-front:
    profiles:
      - "prod"
    build:
      context: ./reparer
      dockerfile: Dockerfile
      target: prod
    image: yassinsiouda/reparer-front:latest
    ports:
      - "8080:80"